# Generated by Django 2.2.7 on 2020-01-26 13:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='添付ファイル')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.Event')),
            ],
        ),
    ]
