# Generated by Django 2.2.7 on 2020-01-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_eventfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventFile',
        ),
    ]
