# Generated by Django 2.2.7 on 2020-01-26 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_delete_eventfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='添付ファイル'),
        ),
    ]
