# Generated by Django 2.2.7 on 2020-02-01 02:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20200126_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentimage',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/mysite/post', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='添付ファイル'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/mysite/post', verbose_name='画像ファイル'),
        ),
        migrations.AlterField(
            model_name='event',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/mysite/event', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/mysite/event', verbose_name='画像ファイル'),
        ),
        migrations.DeleteModel(
            name='ContentFile',
        ),
        migrations.DeleteModel(
            name='ContentImage',
        ),
    ]
