# Generated by Django 2.2.7 on 2020-02-01 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0009_auto_20200202_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='join',
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Join',
        ),
    ]
