# Generated by Django 2.2.7 on 2020-02-03 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0011_auto_20200202_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='value',
            new_name='join_value',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_event', to='mysite.Event')),
                ('user', models.ManyToManyField(blank=True, null=True, related_name='join_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
