# Generated by Django 2.2.7 on 2020-02-03 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_auto_20200203_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='join_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
