# Generated by Django 2.2.7 on 2020-02-04 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_auto_20200203_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='join_post', to='mysite.Post'),
        ),
        migrations.AlterField(
            model_name='join',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='join_event', to='mysite.Event'),
        ),
    ]
