# Generated by Django 2.2.7 on 2020-02-04 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_auto_20200204_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_event', to='mysite.Event'),
        ),
        migrations.AlterField(
            model_name='join',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Post'),
        ),
    ]
