# Generated by Django 2.2.7 on 2020-02-08 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20200205_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_event', to='mysite.Post'),
        ),
    ]
