# Generated by Django 2.2.7 on 2020-02-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_auto_20200208_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='join_level',
            field=models.IntegerField(default=0),
        ),
    ]
