# Generated by Django 2.2.7 on 2020-03-09 14:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0017_event_join_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=140)),
                ('file', models.FileField(blank=True, null=True, upload_to='mysite/file/circular', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('published_at', models.DateField(blank=True, null=True)),
                ('user', models.ManyToManyField(blank=True, related_name='read_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
