# Generated by Django 2.2.7 on 2020-03-12 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_auto_20200312_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circular',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='read_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='join_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Join',
        ),
    ]
