# Generated by Django 2.2.7 on 2020-03-15 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_auto_20200313_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='join_level',
        ),
        migrations.AddField(
            model_name='event',
            name='level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
