# Generated by Django 2.2.7 on 2020-03-29 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_standard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='post_user', to=settings.AUTH_USER_MODEL, verbose_name='read user'),
        ),
    ]
