# Generated by Django 2.2.7 on 2020-03-29 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_auto_20200329_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
