# Generated by Django 2.2.7 on 2020-04-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
