# Generated by Django 2.2.7 on 2020-04-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0027_post_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
