# Generated by Django 2.2.7 on 2020-04-05 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0029_auto_20200405_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='is_public',
        ),
    ]
