# Generated by Django 2.2.7 on 2020-05-06 09:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoronaVirusQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1_1', models.CharField(max_length=20, verbose_name='問1(1):テレワーク、時差出勤"以外"で職場で行っている感染予防対策はありますか。(複数選択可)')),
                ('question1_2', models.CharField(max_length=200, null=True, verbose_name='  (2):(1)で「その他」を選択した方のみお答えください。その他にどのような感染予防対策を行っていますか。')),
                ('question2_1', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='問2(1):テレワーク、時差出勤"以外"で職場で行っている感染予防対策への評価はどれくらいですか。')),
                ('question2_2', models.CharField(max_length=200, null=True, verbose_name='  (2):(1)で「申し分ない」以外を選択した方のみお答えください。どのような点が不十分ですか。')),
                ('question3', models.CharField(max_length=200, null=True, verbose_name='問3:テレワーク、時差出勤"以外"で職場で行って欲しい感染予防対策はありますか。')),
                ('question4_1', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='問4(1):職場でのテレワークの実施率はどれぐらいですか。')),
                ('question4_2', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='  (2):(1)の実施率についての評価はどれくらいですか。')),
                ('question4_3', models.CharField(max_length=200, null=True, verbose_name='  (3):それはなぜですか。')),
                ('question5_1', models.BooleanField(verbose_name='問5(1):今年度テレワークを行いましたか。')),
                ('question5_2', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='  (2):(1)で「はい」の方のみお答えください。テレワークへの評価はどれくらいですか。')),
                ('question5_3', models.CharField(max_length=50, null=True, verbose_name='  (3):(1)で「いいえ」の方のみお答えください。それはなぜですか。')),
                ('question5_4', models.CharField(max_length=200, null=True, verbose_name='  (4):テレワークでの不満点や提案したい改善点があればお答えください。')),
                ('question6', models.CharField(max_length=200, null=True, verbose_name='問6:コロナ禍の情勢において、労働組合に求める働きがあればお答えください。')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='q_set',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionSet',
        ),
    ]
