# Generated by Django 2.2.7 on 2020-05-06 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20200506_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question1_2',
            field=models.CharField(max_length=200, null=True, verbose_name='(2):(1)で「その他」を選択した方のみお答えください。その他にどのような感染予防対策を行っていますか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question2_2',
            field=models.CharField(max_length=200, null=True, verbose_name='(2):(1)で「申し分ない」以外を選択した方のみお答えください。どのような点が不十分ですか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question4_2',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='(2):(1)の実施率についての評価はどれくらいですか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question5_2',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='(2):(1)で「はい」の方のみお答えください。テレワークへの評価はどれくらいですか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question5_3',
            field=models.CharField(max_length=50, null=True, verbose_name='(3):(1)で「いいえ」の方のみお答えください。それはなぜですか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question5_4',
            field=models.CharField(max_length=200, null=True, verbose_name='(4):テレワークでの不満点や提案したい改善点があればお答えください。'),
        ),
    ]
