# Generated by Django 2.2.7 on 2020-05-07 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20200507_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question1_1',
            field=models.CharField(max_length=20, verbose_name='問1(1):テレワーク･時差出勤"以外"で職場で行っている感染予防対策はありますか。(複数選択可)'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question2_1',
            field=models.IntegerField(choices=[(0, '不満'), (1, 'どちらかと言えば不満'), (2, 'どちらとも言えない'), (3, 'どちらかといえば満足'), (4, '満足')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='問2(1):テレワーク･時差出勤"以外"で職場で行っている感染予防対策への評価はどれくらいですか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question2_2',
            field=models.CharField(max_length=200, null=True, verbose_name='(2):(1)で「満足」以外を選択した方のみお答えください。どのような点が不十分ですか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question3',
            field=models.CharField(max_length=200, null=True, verbose_name='問3:テレワーク･時差出勤"以外"で職場で行って欲しい感染予防対策はありますか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question4_2',
            field=models.IntegerField(choices=[(0, '少ない'), (1, 'どちらか言えば少ない'), (2, 'ちょうどよい'), (3, 'どちらかと言えば多い'), (4, '多い')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='(2):(1)の実施率をどう評価してますか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question4_3',
            field=models.CharField(max_length=200, null=True, verbose_name='(3):それはなぜですか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question5_1',
            field=models.BooleanField(choices=[(True, 'はい'), (False, 'いいえ')], verbose_name='問5(1):今年度テレワークを行いましたか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question5_2',
            field=models.IntegerField(choices=[(0, '少ない'), (1, 'どちらか言えば少ない'), (2, 'ちょうどよい'), (3, 'どちらかと言えば多い'), (4, '多い')], null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='(2):(1)で「はい」の方のみお答えください。テレワークへの評価はどれくらいですか。'),
        ),
    ]
