# Generated by Django 2.2.7 on 2020-05-08 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20200507_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronavirusquestion',
            name='question5_5',
            field=models.CharField(max_length=200, null=True, verbose_name='(5):テレワークについて提案したい改善点があればお答えください。(自由回答)'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question1_1',
            field=models.CharField(choices=[(0, '分散職場'), (1, 'デスク間･窓口へのパーテーション等設置'), (2, '定期的な窓開け等による換気'), (3, '電話機の増設による使い回しの防止'), (4, 'その他')], max_length=20, verbose_name='問1(1)テレワーク･時差出勤"以外"で職場で行っている感染予防対策はありますか。(複数選択可)'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question1_2',
            field=models.CharField(max_length=100, null=True, verbose_name='(2):(1)で「その他」を選択した方のみお答えください。その他にどのような感染予防対策を行っていますか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question2_1',
            field=models.IntegerField(choices=[(0, '不満'), (1, 'どちらかと言えば不満'), (2, 'どちらとも言えない'), (3, 'どちらかといえば満足'), (4, '満足')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='問2(1)テレワーク･時差出勤"以外"で職場で行っている感染予防対策への評価はどれくらいですか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question2_2',
            field=models.CharField(max_length=100, null=True, verbose_name='(2):(1)で「満足」以外を選択した方のみお答えください。どのような点が不十分ですか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question3',
            field=models.CharField(max_length=200, null=True, verbose_name='問3テレワーク･時差出勤"以外"で職場で行って欲しい感染予防対策はありますか。(自由回答)'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question4_1',
            field=models.IntegerField(choices=[(0, '0％(職場のほぼ誰も取得したことがない)'), (1, '0％~20％(毎日職場の2割以下がローテーションで取得)'), (2, '20％~40%(毎日職場の2割から4割程度がローテーションで取得)'), (3, '40％~60%(毎日職場の4割から6割程度がローテーションで取得)'), (4, '60%~(毎日職場の6割以上がローテーションで取得)')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='問4(1)職場でのテレワークの実施率はどれぐらいですか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question4_3',
            field=models.CharField(max_length=100, null=True, verbose_name='(3)それはなぜですか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question5_1',
            field=models.BooleanField(choices=[(True, 'はい'), (False, 'いいえ')], verbose_name='問5(1)今年度あなたはテレワークを行いましたか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question5_2',
            field=models.IntegerField(choices=[(0, '不満'), (1, 'どちらかと言えば不満'), (2, 'どちらとも言えない'), (3, 'どちらかといえば満足'), (4, '満足')], null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='(2):(1)で「はい」の方のみお答えください。テレワークへの評価はどれくらいですか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question5_3',
            field=models.CharField(max_length=200, null=True, verbose_name='(2):(1)で「はい」の方のみお答えください。テレワークを行った上での不満点、またよかった点をお答えください。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question5_4',
            field=models.CharField(max_length=50, null=True, verbose_name='(4):(1)で「いいえ」の方のみお答えください。それはなぜですか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question6',
            field=models.CharField(max_length=100, null=True, verbose_name='問6コロナ禍の情勢において、労働組合に求める働きをお答えください(自由回答)。'),
        ),
    ]
