# Generated by Django 2.2.7 on 2020-05-10 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20200508_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question1_1',
            field=models.CharField(choices=[(0, 'オフィスの密集を避けるための職場分散の実施'), (1, 'デスク間･窓口へのパーテーション等設置'), (2, '定期的な窓開け等による換気'), (3, 'アルコール･除菌シート等の衛生用品の設置'), (4, 'その他')], max_length=20, verbose_name='問1(1)テレワーク･時差出勤"以外"で職場で行っている感染予防対策はありますか。(複数選択可)'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question1_2',
            field=models.CharField(max_length=100, null=True, verbose_name='(2)(1)で「その他」を選択した方のみお答えください。その他にどのような感染予防対策を行っていますか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question2_2',
            field=models.CharField(max_length=100, null=True, verbose_name='(2)(1)で「満足」以外を選択した方のみお答えください。どのような点が不十分ですか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question4_2',
            field=models.IntegerField(choices=[(0, '少ない'), (1, 'どちらか言えば少ない'), (2, 'ちょうどよい'), (3, 'どちらかと言えば多い'), (4, '多い')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='(2)(1)の実施率をどう評価してますか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question5_2',
            field=models.IntegerField(choices=[(0, '不満'), (1, 'どちらかと言えば不満'), (2, 'どちらとも言えない'), (3, 'どちらかといえば満足'), (4, '満足')], null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='(2)(1)で「はい」の方のみお答えください。テレワークへの評価はどれくらいですか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question5_3',
            field=models.CharField(max_length=200, null=True, verbose_name='(3)(1)で「はい」の方のみお答えください。テレワークを行った上での不満点、またよかった点をお答えください。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question5_4',
            field=models.CharField(max_length=50, null=True, verbose_name='(4)(1)で「いいえ」の方のみお答えください。それはなぜですか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question5_5',
            field=models.CharField(max_length=200, null=True, verbose_name='(5)テレワークについて提案したい改善点があればお答えください。(自由回答)'),
        ),
    ]
