# Generated by Django 2.2.7 on 2020-05-12 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_auto_20200510_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coronavirusquestion',
            name='question6',
        ),
        migrations.AddField(
            model_name='coronavirusquestion',
            name='question6_1',
            field=models.CharField(max_length=100, null=True, verbose_name='問6(1)コロナ禍の情勢において、職制側に求める施策をお答えください。'),
        ),
        migrations.AddField(
            model_name='coronavirusquestion',
            name='question6_2',
            field=models.CharField(max_length=100, null=True, verbose_name='問6(2)コロナ禍の情勢において、労働組合に求める働きをお答えください。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question2_1',
            field=models.IntegerField(choices=[(0, '不満'), (1, 'どちらかと言えば不満'), (2, 'どちらとも言えない'), (3, 'どちらかと言えば満足'), (4, '満足')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='問2(1)テレワーク･時差出勤"以外"で職場で行っている感染予防対策への評価はどれくらいですか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question3',
            field=models.CharField(max_length=200, null=True, verbose_name='問3テレワーク･時差出勤"以外"で職場で行って欲しい感染予防対策はありますか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question4_3',
            field=models.CharField(max_length=100, null=True, verbose_name='(3)(2)の評価の理由はなぜですか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question5_2',
            field=models.IntegerField(choices=[(0, '不満'), (1, 'どちらかと言えば不満'), (2, 'どちらとも言えない'), (3, 'どちらかと言えば満足'), (4, '満足')], null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='(2)(1)で「はい」の方のみお答えください。テレワークへの評価はどれくらいですか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question5_5',
            field=models.CharField(max_length=200, null=True, verbose_name='(5)テレワークについて職制側に提案したい改善点があればお答えください。'),
        ),
    ]
