# Generated by Django 2.2.7 on 2020-05-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20200512_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question5_2',
            field=models.IntegerField(choices=[(0, '不満'), (1, 'どちらかと言えば不満'), (2, 'どちらとも言えない'), (3, 'どちらかと言えば満足'), (4, '満足')], null=True, verbose_name='(2)(1)で「はい」の方のみお答えください。テレワークへの評価はどれくらいですか。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question6_2',
            field=models.CharField(max_length=100, null=True, verbose_name='(2)コロナ禍の情勢において、労働組合に求める働きをお答えください。'),
        ),
    ]
