# Generated by Django 2.2.7 on 2020-05-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20200512_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronavirusquestion',
            name='question7_1',
            field=models.CharField(max_length=100, null=True, verbose_name='問7(1)コロナ禍の情勢において、職制側に求める施策をお答えください。'),
        ),
        migrations.AddField(
            model_name='coronavirusquestion',
            name='question7_2',
            field=models.CharField(max_length=100, null=True, verbose_name='(2)コロナ禍の情勢において、労働組合に求める働きをお答えください。'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question1_1',
            field=models.CharField(max_length=20, verbose_name='問1(1)テレワーク･時差出勤"以外"で職場で行っている感染予防対策はありますか。(複数選択可)'),
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question6_1',
            field=models.BooleanField(choices=[(True, 'はい'), (False, 'いいえ')], default=True, verbose_name='問6(1)今後もテレワーク業務の継続を望みますか'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coronavirusquestion',
            name='question6_2',
            field=models.CharField(max_length=200, null=True, verbose_name='(2)(1)の理由はなぜですか'),
        ),
    ]
