# Generated by Django 2.2.7 on 2020-01-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200121_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='sections',
            field=models.ManyToManyField(null=True, related_name='section_sets', to='register.Section', verbose_name='課'),
        ),
    ]
