# Generated by Django 2.2.7 on 2020-01-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200121_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='sections',
        ),
        migrations.AddField(
            model_name='section',
            name='departments',
            field=models.ManyToManyField(null=True, related_name='department_sets', to='register.Department', verbose_name='部'),
        ),
    ]
