# Generated by Django 2.2.7 on 2020-01-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200122_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='departments',
        ),
        migrations.AddField(
            model_name='department',
            name='sections',
            field=models.ManyToManyField(null=True, related_name='section_sets', to='register.Section', verbose_name='課'),
        ),
    ]
