# Generated by Django 2.2.7 on 2020-01-31 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20200201_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='section',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='section',
        ),
        migrations.AddField(
            model_name='department',
            name='sections',
            field=models.ManyToManyField(null=True, related_name='section_sets', to='register.Section', verbose_name='課'),
        ),
        migrations.AddField(
            model_name='user',
            name='departments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_set', related_query_name='department', to='register.Department', verbose_name='部'),
        ),
        migrations.AddField(
            model_name='user',
            name='sections',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_set', related_query_name='section', to='register.Section', verbose_name='課'),
        ),
    ]
