# Generated by Django 2.2.7 on 2020-02-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20200201_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='section',
            field=models.ManyToManyField(related_name='D_section_set', to='register.Section', verbose_name='課'),
        ),
    ]
