# Generated by Django 2.2.7 on 2020-03-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20200201_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_executive',
            new_name='level',
        ),
    ]
