# Generated by Django 2.2.7 on 2020-04-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20200315_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='union_class',
            field=models.CharField(blank=True, default='なし', max_length=20, null=True, verbose_name='役職'),
        ),
    ]
