# Generated by Django 2.2.7 on 2020-05-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_user_union_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='user',
            name='union_class',
            field=models.CharField(blank=True, default='なし', max_length=20, verbose_name='役職'),
        ),
    ]
