# Generated by Django 2.2.7 on 2020-05-06 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_auto_20200506_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='アカウント作成日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='アカウントの有無'),
        ),
        migrations.AlterField(
            model_name='user',
            name='union_class',
            field=models.CharField(blank=True, default='なし', max_length=20, verbose_name='役職名'),
        ),
    ]
